// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DAL.ContextClasses;

#nullable disable

namespace Project.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240121185251_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "468f9bee-b0cc-4bed-acfb-0846c210a137",
                            Name = "Creator",
                            NormalizedName = "CREATOR"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "09daffee-ff04-41d1-aead-7eedca95fe30",
                            Name = "Responder",
                            NormalizedName = "RESPONDER"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "8dec57d4-89a0-4f3c-8ddc-e404fa8f1ffa",
                            Name = "Analyzer",
                            NormalizedName = "ANALYZER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9888),
                            QuestionId = 1,
                            Status = (byte)1,
                            Text = "Çok memnunum"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9893),
                            QuestionId = 1,
                            Status = (byte)1,
                            Text = "Memnun değilim"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9896),
                            QuestionId = 2,
                            Status = (byte)1,
                            Text = "Mükemmel"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9898),
                            QuestionId = 2,
                            Status = (byte)1,
                            Text = "İyileştirilebilir"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9900),
                            QuestionId = 3,
                            Status = (byte)1,
                            Text = "Çok fazla fayda sağladım"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9904),
                            QuestionId = 3,
                            Status = (byte)1,
                            Text = "Yeterli değil"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9907),
                            QuestionId = 4,
                            Status = (byte)1,
                            Text = "Evet, tam olarak"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9909),
                            QuestionId = 4,
                            Status = (byte)1,
                            Text = "Hayır, daha fazla esneklik istiyorum"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9911),
                            QuestionId = 5,
                            Status = (byte)1,
                            Text = "Memnunum"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9914),
                            QuestionId = 5,
                            Status = (byte)1,
                            Text = "Daha fazla geribildirim bekliyorum"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9916),
                            QuestionId = 6,
                            Status = (byte)1,
                            Text = "Hayır, güvenli hissediyorum"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9918),
                            QuestionId = 6,
                            Status = (byte)1,
                            Text = "Evet, iyileştirmeler yapılmalı"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9920),
                            QuestionId = 7,
                            Status = (byte)1,
                            Text = "Yönetilebilir"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 91, DateTimeKind.Local).AddTicks(9922),
                            QuestionId = 7,
                            Status = (byte)1,
                            Text = "Yüksek"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7f6dd10-cf9e-4c40-aefc-bfe5c4cfb4a7",
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 92, DateTimeKind.Local).AddTicks(5929),
                            Email = "creator@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            Name = "Kemal",
                            NormalizedEmail = "CREATOR@GMAIL.COM",
                            NormalizedUserName = "CREATOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEIQ3WAJ2Fpm3Wxn207ffi9OXYUbeGSKZ6lkFb4U9rairXJ2FBHhRcIUK1V5uWbr7XA==",
                            PhoneNumber = "5312292928",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "93601eac-ec99-477e-8047-1d97eb4daec9",
                            Status = (byte)1,
                            SurName = "Akcan",
                            TwoFactorEnabled = false,
                            UserName = "Creator"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "29d232cc-5f15-4dd7-8ba0-f8df082576df",
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 92, DateTimeKind.Local).AddTicks(5964),
                            Email = "responder@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            Name = "Sefa",
                            NormalizedEmail = "RESPONDER@GMAIL.COM",
                            NormalizedUserName = "RESPONDER",
                            PasswordHash = "AQAAAAEAACcQAAAAEKQFlAEmqcUzmw37MiyjiaxERli8TKD0oMPaAs03dRk1Yq3vNy4C02Ca0upTPqOjwA==",
                            PhoneNumber = "5446340539",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "4665c646-a23f-4087-88ef-448add2ee2a2",
                            Status = (byte)1,
                            SurName = "Er",
                            TwoFactorEnabled = false,
                            UserName = "Responder"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "82e80d88-0ef5-49fb-96e6-bdfc7af3628a",
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 92, DateTimeKind.Local).AddTicks(5980),
                            Email = "analyzer@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            Name = "Bora",
                            NormalizedEmail = "ANALYZER@GMAIL.COM",
                            NormalizedUserName = "ANALYZER",
                            PasswordHash = "AQAAAAEAACcQAAAAEN6X5/oCCvV6zd4uMXnQWddnboPsGgZoG1TQgAxuyc/BMDeX4nugQY2Beg8eD0+UlA==",
                            PhoneNumber = "5446340539",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "6b405c39-e284-4fd5-aee0-032c7610fed0",
                            Status = (byte)1,
                            SurName = "Öz",
                            TwoFactorEnabled = false,
                            UserName = "Analyzer"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserAnswer", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("AppUserId", "AnswerId");

                    b.HasIndex("AnswerId");

                    b.ToTable("AppUserAnswers");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserSurvey", b =>
                {
                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Score")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("AppUserId", "SurveyId");

                    b.HasIndex("SurveyId");

                    b.ToTable("AppUserSurveys");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "A",
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(123),
                            Score = (byte)10,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            Code = "B",
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(130),
                            Score = (byte)6,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Code = "C",
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(133),
                            Score = (byte)8,
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsItAnswered")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentQuestionId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("SurveyId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ParentQuestionId");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(1432),
                            GroupId = 3,
                            IsItAnswered = false,
                            Status = (byte)1,
                            SurveyId = 1,
                            Text = "İş yerindeki genel çalışma ortamından ne kadar memnunsunuz?"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(1436),
                            GroupId = 2,
                            IsItAnswered = false,
                            Status = (byte)1,
                            SurveyId = 1,
                            Text = "Takım arkadaşlarıyla iletişim ve işbirliği konusundaki deneyimleriniz nedir?"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(1440),
                            GroupId = 1,
                            IsItAnswered = false,
                            ParentQuestionId = 2,
                            Status = (byte)1,
                            SurveyId = 1,
                            Text = "Şirket tarafından sunulan eğitim ve gelişim fırsatlarından ne kadar faydalandınız?"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(1442),
                            GroupId = 2,
                            IsItAnswered = false,
                            ParentQuestionId = 2,
                            Status = (byte)1,
                            SurveyId = 1,
                            Text = "Çalışma saatleri ve esneklik konusundaki beklentilerinizi karşılayabiliyor musunuz?"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(1444),
                            GroupId = 3,
                            IsItAnswered = false,
                            Status = (byte)1,
                            SurveyId = 1,
                            Text = "Performans değerlendirmelerinizle ilgili olarak geribildirim almak konusundaki memnuniyetiniz nedir?"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(1450),
                            GroupId = 2,
                            IsItAnswered = false,
                            ParentQuestionId = 5,
                            Status = (byte)1,
                            SurveyId = 1,
                            Text = "İş güvenliği önlemleri ve çalışma ortamı konusunda endişeleriniz var mı?"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(1452),
                            GroupId = 2,
                            IsItAnswered = false,
                            Status = (byte)1,
                            SurveyId = 1,
                            Text = "İş yükü ve stres seviyeleriniz hakkında nasıl hissediyorsunuz?"
                        });
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Surveys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 1, 21, 21, 52, 51, 99, DateTimeKind.Local).AddTicks(2218),
                            Name = "İşyeri Memnuniyeti",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Answer", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserAnswer", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Answer", "Answer")
                        .WithMany("AppUserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("AppUserAnswers")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUserSurvey", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("AppUserSurveys")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Survey", "Survey")
                        .WithMany("AppUserSurveys")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Question", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.Group", "Group")
                        .WithMany("Questions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.ENTITIES.Models.Question", "ParentQuestion")
                        .WithMany("ChildQuestions")
                        .HasForeignKey("ParentQuestionId");

                    b.HasOne("Project.ENTITIES.Models.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("ParentQuestion");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Survey", b =>
                {
                    b.HasOne("Project.ENTITIES.Models.AppUser", "AppUser")
                        .WithMany("Surveys")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Answer", b =>
                {
                    b.Navigation("AppUserAnswers");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.AppUser", b =>
                {
                    b.Navigation("AppUserAnswers");

                    b.Navigation("AppUserSurveys");

                    b.Navigation("Surveys");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Group", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ChildQuestions");
                });

            modelBuilder.Entity("Project.ENTITIES.Models.Survey", b =>
                {
                    b.Navigation("AppUserSurveys");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
